---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  yum_repository:
    name: enable repos
    description: enable repos
    file: external_repos
    baseurl: https://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
    enabled: yes
 
- name: install base tools and packages

